I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script
    define p = Character(player_name, dynamic=True, color="#000000")
  File "game/script.rpy", line 19, in <module>
    define p = Character(player_name, dynamic=True, color="#000000")
NameError: name 'player_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script
    define p = Character(player_name, dynamic=True, color="#000000")
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/ast.py", line 2508, in execute
    self.set()
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 19, in <module>
    define p = Character(player_name, dynamic=True, color="#000000")
NameError: name 'player_name' is not defined

macOS-13.2.1-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
kaistmossolescape 1.0
Sat Jul 15 14:09:53 2023
