I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 790, in script
    jump scene14_a
ScriptError: could not find label 'scene14_a'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 790, in script
    jump scene14_a
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'scene14_a'.

macOS-13.2.1-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
kaistmossolescape 1.0
Tue Jul 18 17:30:33 2023
