I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script
    image Hiyori = Live2D("Resources/Hiyori", base=.6, loop=True)
  File "game/script.rpy", line 15, in <module>
    image Hiyori = Live2D("Resources/Hiyori", base=.6, loop=True)
Exception: Could not load Live2D. b'libLive2DCubismCore.dylib' was not found.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script
    image Hiyori = Live2D("Resources/Hiyori", base=.6, loop=True)
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/ast.py", line 1237, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 15, in <module>
    image Hiyori = Live2D("Resources/Hiyori", base=.6, loop=True)
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/gl2/live2d.py", line 566, in __init__
    common = self.create_common(default_fade)
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/gl2/live2d.py", line 510, in create_common
    rv = Live2DCommon(self.filename, default_fade)
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/gl2/live2d.py", line 186, in __init__
    init()
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/gl2/live2d.py", line 93, in init
    onetime_init()
  File "/Users/taeyunroh/Documents/renpy-8.1.1-sdk/renpy/gl2/live2d.py", line 66, in onetime_init
    raise Exception("Could not load Live2D. {} was not found.".format(dll))
Exception: Could not load Live2D. b'libLive2DCubismCore.dylib' was not found.

macOS-13.2.1-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
kaistmossolescape 1.0
Sat Jul 15 15:52:12 2023
